channels:
  - pytorch
  - defaults

dependencies:
  - pytorch=1.11.0
  - torchvision=0.12.0
  - torchaudio=0.11.0
  - cudatoolkit=11.3
  - mkl<2024.0
  - intel-openmp<2024.0
  - pillow=9.0.1
  - pip=21.2.4
  
  - pip:
    - numpy==1.26.4
    - open3d==0.19.0
    - opencv-python==4.10.0.84
    - pytorch-lightning==1.6.4
    - einops==0.6.0
    - einops-exts==0.0.4
    - scikit-image==0.19.2
    - scikit-learn==1.2.1
    - matplotlib==3.6.3
    - pandas==1.4.2
    - tensorboard==2.9.0
    - torch-tb-profiler==0.4.3
    - torchmetrics==0.9.0
    - trimesh==3.12.5
    - plyfile==0.7.4
    - pyquaternion==0.9.9
    - rotary-embedding-torch==0.2.1
    - configargparse==1.5.3
    - tqdm==4.64.0
    - pyyaml==6.0
    - imageio==2.19.3
    - networkx==2.8.2
    - dash==2.8.1
    - plotly==5.13.0
    - ipykernel==6.21.1
    - ipython==8.10.0
    - ipywidgets==8.0.4
